version: "3"

services:
  gs-app: 
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - database_mysql
  database_mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"